### ISSUE TITLE
Nice idea

### ISSUE THREAD

**Issue by alexellis** [skyao/learning-openfaas#1]
Hey @skyao - I am the author of OpenFaaS and I just saw this repo and wanted to check it out.

How far have you got?

Would you like to join our Slack community and get connected to the project? We'd really like to have you join us.

Alex

**Comment by skyao** [comment]
Hi, Alux, thank you for your invention. I have join slack.

This "learning-openfaas" repo will be used to hold a ebook in the format of gitbook and in Chinese. I will start this book soon.

At the last, Open FaaS is a great project. Thank you to bring it to us.

**Comment by alexellis** [comment]
Looking forward to seeing you there
